spring.application.name=atrilha
server.port=8084

management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=health
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
